### ISSUE TITLE
coco-stuff dataset had been filtered？

### ISSUE THREAD

**Issue by why529913** [KaiChen1998/GeoDiffusion#10]
I used coco-stuff to train data collection 256x256 and found that the fid accuracy is low. I looked at the paper and found that the data had been filtered. Is this the reason? Can you provide the dataset in the paper?

**Comment by KaiChen1998** [comment]
As claimed in the README file, you can find our converted annotation file for COCO-Stuff [here](https://huggingface.co/datasets/KaiChen1998/coco-stuff-geodiffusion). We follow [LAMA](https://github.com/ZejianLi/LAMA) to deal with the original annotations.
