### ISSUE TITLE
Training on custom dataset (KITTI)

### ISSUE THREAD

**Issue by joonjeon** [KaiChen1998/GeoDiffusion#12]
I am trying to use your work to train on KITTI dataset, but it does not work.

Error message says that `num_samples` becomes zero.

The following is my directory tree for the KITTI dataset:
[kitti-tree.txt](https://github.com/user-attachments/files/15880802/kitti-tree.txt)

Any ideas on why this is happening?

**Comment by KaiChen1998** [comment]
@joonjeon It seems like you might not construct the COCO-style annotation file correctly, and therefore, resulting in `num_samples=0` even if there are indeed images saved in your directory tree. I do recommend you to check [here](https://mmdetection.readthedocs.io/en/latest/user_guides/train.html#coco-annotation-format) to get familiar with the COCO-format, [here](https://github.com/open-mmlab/mmdetection/blob/v2.25.3/mmdet/datasets/coco.py#L121) to check the detailed image filtering procedure of COCO dataset, and [here](https://mmdetection3d.readthedocs.io/en/latest/advanced_guides/datasets/kitti.html) to get more familiar with the KITTI official annotation format.

**Comment by joonjeon** [comment]
Alright. Thanks a lot for your help.
