### ISSUE TITLE
 no file named pytorch_model.bin, model.safetensors, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory

### ISSUE THREAD

**Issue by 0708DjN** [KaiChen1998/GeoDiffusion#15]
Hello！When I try to load the model that I downloaded from Huggingface, I get an error which says the model is missing the corresponding file, do I need to add other files? Hope you can reply.

**Comment by KaiChen1998** [comment]
First, check whether or not you have downloaded all the files of the checkpoint you are using from HuggingFace. After that, check whether you have provided the correct path name to your function. Finally, check the `diffusers` and `transformers` versions. Please follow our requirements [here](https://github.com/KaiChen1998/GeoDiffusion/tree/main/requirements) to run our models.
