### ISSUE TITLE
Trainability: Faster R-CNN training- input resize of real Images?

### ISSUE THREAD

**Issue by why529913** [KaiChen1998/GeoDiffusion#18]
Could you tell me
1. In the Trainability chapter, do both Nuimages and COCO use Faster R-CNN detectors?
2. When training Faster R-CNN, is the size also resized to 800x456? Or is it another size?
Thank you very much.

**Comment by KaiChen1998** [comment]
1. Yes, we use Faster R-CNN based on the implementation of [mmdet](https://github.com/open-mmlab/mmdetection/tree/v2.25.3).
2. Yes, we resize the real and generated images to 800x456.
