### ISSUE TITLE
COCO dataset's Trainablity？

### ISSUE THREAD

**Issue by why529913** [KaiChen1998/GeoDiffusion#19]
I see that nuimages' Trainablity is trained with 800x456 GeoDiffusion. Is the COCO dataset's Trainablity also trained with 800x456 GeoDiffusion input size? Or is it 512x512?

**Comment by KaiChen1998** [comment]
The basic idea is to keep the training resolution consistent with the resolution of the generated images. 

Therefore yes, the training size on COCO experiments is also 800x456.
