### ISSUE TITLE
Inquire about the trainability experiments.

### ISSUE THREAD

**Issue by haoweiz23** [KaiChen1998/GeoDiffusion#22]
Dear authors,

I wonder how many data have you generate for the CoCo trainability experiments (Table 5 in the paper)? Is the same amount as CoCo train set?

**Comment by KaiChen1998** [comment]
1. Not exactly. As stated in `Sec. 4.2.2 Setup` paragraph, we first conduct annotation cleaning for the original COCO annotations, and we will only generate images for those samples with valid annotations.
2. As stated in Table 2, the primary improvement generated data brings is for long-tailed classes. Thus, we recommend you consider more of those rare cases in the COCO dataset for more significant improvements brought by generated data.

**Comment by haoweiz23** [comment]
Thank you for your response. To confirm my understanding: You filter and augment the original bounding box annotations in the COCO training set, and then use these filtered annotations to generate training samples. The number of generated samples is less than the original training set due to the filtering process. Afterward, you concatenate the generated dataset with the original dataset to train the Faster R-CNN R50 model using a 1x schedule. Is that correct?

**Comment by KaiChen1998** [comment]
Exactly.

**Comment by KaiChen1998** [comment]
Feel free to re-open this issue if necessary.
