### ISSUE TITLE
Why are the results or md5 all the same after multiple inferences when using the same layout？

### ISSUE THREAD

**Issue by zhangxiao696** [KaiChen1998/GeoDiffusion#5]
Normally，the generate result should be different every time when use the same layout and prompt. But, use your model, the result and md5 of image are all the same

**Comment by KaiChen1998** [comment]
Thank you for your interest in our work! Normally for reproductivity, we could set the random seed to a fixed value like [here](https://github.com/KaiChen1998/GeoDiffusion/blob/main/run_layout_to_image.py#L12). Therefore, to generate multiple different images with the same input layout, you might simply comment out this line.
