### ISSUE TITLE
 Congratulations on Your Paper Being Accepted to ICLR 2024!

### ISSUE THREAD

**Issue by CatLoves** [KaiChen1998/GeoDiffusion#6]
Dear Chen, Kai and Xie, Enze and Chen, Zhe and Hong, Lanqing and Li, Zhenguo and Yeung, Dit-Yan,

I hope this message finds you well. I am writing to extend my heartfelt congratulations to you and your co-authors on the acceptance of your paper, "GeoDiffusion: Text-Prompted Geometric Control for Object Detection Data Generation," to the International Conference on Learning Representations (ICLR) 2024!

Your achievement reflects the dedication, hard work, and innovative thinking that went into your research. ICLR is one of the premier conferences in machine learning and artificial intelligence, and being accepted to present your work there is a significant recognition of its quality and impact on the field.

On behalf of the open source community, I want to express our sincere appreciation for your contributions to advancing the frontiers of knowledge in machine learning. Your research not only pushes the boundaries of what is possible but also inspires others in our community to explore new ideas and approaches.

Additionally, I would like to extend our gratitude for your commitment to open science and sharing your knowledge with the community. It is through the generosity of researchers like you that we can collectively accelerate progress and foster collaboration in the field.

In light of the importance of reproducibility and open access to research, we kindly request your assistance in making the training code associated with your paper publicly available. Having access to the training code would greatly benefit researchers and practitioners interested in replicating and building upon your findings.

As a token of our appreciation, we would like to offer our assistance in any way possible. Whether it be providing support with open-sourcing the training code associated with your paper or promoting your work through our channels, please do not hesitate to reach out to us.

Once again, congratulations on this well-deserved accomplishment! We look forward to seeing your presentation at ICLR 2024 and witnessing the continued impact of your research in the years to come.

Warm regards,
CatLoves

**Comment by lifrary** [comment]
+1

**Comment by KaiChen1998** [comment]
@CatLoves @lifrary Thank you for your interest and great patience in our work! We are glad to announce that the training code has recently been updated! Welcome to use and leave comments!
